---
networks:
  k3s-local:
    name: k3s-local
services:
  k3s-agent:
    container_name: k3s-agent
    depends_on:
      - k3s-server
    environment:
      - K3S_URL=https://k3s-server:6443
      - K3S_TOKEN=ccb18c28-ac5a-11ec-b909-0242ac120002
    hostname: k3s-agent
    image: rancher/k3s:latest
    networks:
      - k3s-local
    privileged: true
    restart: always
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nofile:
        hard: 65535
        soft: 65535
      nproc: 65535
  k3s-server:
    command: server --disable traefik,metrics-server
    container_name: k3s-server
    environment:
      - K3S_TOKEN=ccb18c28-ac5a-11ec-b909-0242ac120002
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    hostname: k3s-server
    image: rancher/k3s:latest
    networks:
      - k3s-local
    ports:
      - '6443:6443'
      - '80:80'
      - '443:443'
    privileged: true
    restart: always
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nofile:
        hard: 65535
        soft: 65535
      nproc: 65535
    volumes:
      - k3s-server:/var/lib/rancher/k3s
      - .:/output
version: '3.9'
volumes:
  k3s-server:
    name: k3s-server