---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-producer
  namespace: kafka-producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - command:
            - /scripts/run.sh
          env:
            - name: KAFKA_BROKERS
              value: kafka:9092
            - name: KAFKA_TOPIC
              value: test
          image: confluentinc/cp-kafkacat:7.0.1
          imagePullPolicy: IfNotPresent
          name: kafka-producer
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
          volumeMounts:
            - mountPath: /scripts
              name: run-script
      serviceAccountName: kafka-producer
      terminationGracePeriodSeconds: 0
      volumes:
        - configMap:
            defaultMode: 0744
            name: run-script
          name: run-script
---
apiVersion: v1
data:
  run.sh: |
    #!/usr/bin/env bash
    echo "kafkacat -P -b ${KAFKA_BROKERS} -t ${KAFKA_TOPIC} -T -l /tmp/msgs -K:"
    i=0
    while true ; do 
      echo -e ${i}:$(date +"%Y-%m-%dT%H:%M:%S") > /tmp/msgs
      kafkacat -P -b ${KAFKA_BROKERS} -t ${KAFKA_TOPIC} -T -l /tmp/msgs -K:
      sleep 1
      let "i=i+1"
    done
kind: ConfigMap
metadata:
  name: run-script
  namespace: kafka-producer